[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[project]
name = "michaelmendoza/ssfp"
version = "0.0.1"
authors = [
  { name="Michael Mendoza", email="askmichaelmendoza@gmail.com" },
]
description = "SSFP Simulation Package"
readme = "README.md"
requires-python = ">=3.8"
classifiers = [
    "Programming Language :: Python :: 3",
    "License :: OSI Approved :: MIT License",
    "Operating System :: OS Independent",
]

[project.urls]
"Homepage" = "https://github.com/michaelmendoza/ssfp"
"Bug Tracker" = "https://github.com/michaelmendoza/ssfp/issues"